image:https://img.shields.io/github/actions/workflow/status/Breus/json-masker/build.yml[GitHub Workflow Status (with event),link="https://github.com/Breus/json-masker/actions/workflows/build.yml"]
image:https://img.shields.io/maven-central/v/dev.blaauwendraad/json-masker[Maven Central,link="https://central.sonatype.com/artifact/dev.blaauwendraad/json-masker"]

= High-performance JSON masker

JSON masker which can be used to mask strings and numbers from JSON messages, corresponding to a (set of) target key(s).
Alternatively, it can be used to mask all strings and numbers from a JSON message except the ones corresponding to the target keys.

The library provides a convenient API and its implementation is focused on maximum (time) performance using Java.
No additional third-party runtime dependencies are required for this library.

== Features

- Mask strings in any JSON structure corresponding to configured target keys (default)
- Mask numbers in any JSON structure corresponding to configured target keys (optional)
- Obfuscate the original length of the masked value by using a fixed-length mask (optional)
- Target key case sensitivity configuration (default: `false`)
- Block-list (`masked`) or allow-list (`allowed`) interpretation of target key set (default: `masked`)
- The implementation only supports JSON in UTF-8 character encoding

== Roadmap features

- Support for masking strings and numbers inside (nested) arrays
- JSONPath support for target keys

== Usage examples

=== Default JSON masking

Example showing masking certain specific JSON properties containing personal identifiable information (PII) in the message.

==== Input

[source,json]
----
{
    "orderId": "789 123 456",
    "customerDetails": {
        "id": "123 789 456",
        "email": "some-customer-email@example.com",
        "iban": "NL91 FAKE 0417 1643 00"
    }
}
----

==== Usage

[source,java]
----
String output = JsonMasker.getMasker(Set.of("email", "iban")).mask(input);
----

==== Output

[source,json]
----
{
    "orderId": "789 123 456",
    "customerDetails": {
        "id": "123 789 456",
        "email": "*******************************",
        "iban": "**********************"
    }
}
----

=== Masking with length obfuscation

Example showing masking where the original length of the masked value is obfuscated besides the value being masked.

==== Input

[source,json]
----
{
    "sessionId": "123_456_789_098",
    "clientPin": "234654"
}
----

==== Usage

[source,java]
----
String output = JsonMasker.getMasker(JsonMaskingConfig.custom(
        Set.of("clientPin"),
        JsonMaskingConfig.TargetKeyMode.MASK
).obfuscationLength(3).build()).mask(input);
----

==== Output

[source,json]
----
{
    "sessionId": "123_456_789_098",
    "clientPin": "***"
}

----

=== Allow-list approach and number masking

Example showing an allow-list based approach of masking JSON where additionally all numbers are masked by replacing them with an '8'.

==== Input

[source,json]
{
    "customerId": "123 789 456",
    "customerDetails": {
        "firstName": "Breus",
        "lastName": "Blaauwendraad",
        "email": "some-fake-email@example.com",
        "age": 37
    }
}

==== Usage

[source,java]
String output = JsonMasker.getMasker(JsonMaskingConfig.custom(
        Set.of("customerId"),
        JsonMaskingConfig.TargetKeyMode.ALLOW
).maskNumberValuesWith(8).build()).mask(input);

==== Output

[source,json]
{
    "customerId": "123 789 456",
    "customerDetails": {
        "firstName": "*****",
        "lastName": "**************",
        "email": "***************************",
        "age": 88
    }
}

== Dependencies

* **The library has no third-party runtime dependencies**
* The library only has a single JSR-305 compilation dependency
* The test/benchmark dependencies for this library are listed in the `build.gradle`

== Performance considerations

This library uses a dedicated multi-target algorithm by looking for a JSON key and checking whether the target key set
contains this key in constant time.

The time complexity of this algorithm scales only linear in the message input length.
Additionally, the target key set size has negligible impact on the performance.


== Benchmarks

[source]
----
Benchmark                           (jsonSize)  (numberOfKeys)   Mode        Score  Units
BaselineBenchmark.noop                     4kb             100  thrpt  1567094.010  ops/s
BaselineBenchmark.jackson                  4kb             100  thrpt    75569.597  ops/s
JsonMaskerBenchmark.maskJsonBytes          4kb             100  thrpt   405496.513  ops/s
JsonMaskerBenchmark.maskJsonString         4kb             100  thrpt   346559.740  ops/s

BaselineBenchmark.noop                     2mb             100  thrpt     2263.683  ops/s
BaselineBenchmark.jackson                  2mb             100  thrpt        7.923  ops/s
JsonMaskerBenchmark.maskJsonBytes          2mb             100  thrpt     2493.899  ops/s
JsonMaskerBenchmark.maskJsonString         2mb             100  thrpt     1312.198  ops/s
----

For full benchmark results see link:jmh/benchmark-history[jmh/benchmark-history]

