name: Build
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          path: benchmark-master

      - uses: actions/checkout@v4
        with:
          path: benchmark-pull-request

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run benchmarks (pull-request)
        working-directory: benchmark-pull-request
        run: |
          ./gradlew jmh -PjmhShort
          echo "### Benchmark results (pull-request)" >> ../benchmark-comment.md
          echo "```text" >> ../benchmark-comment.md
          cat build/results/jmh/results.txt >> ../benchmark-comment.md
          echo "```" >> ../benchmark-comment.md

      - name: Run benchmarks (master)
        working-directory: benchmark-master
        run: |
          ./gradlew jmh -PjmhShort
          echo "### Benchmark results (master)" >> ../benchmark-comment.md
          echo "```text" >> ../benchmark-comment.md
          cat build/results/jmh/results.txt >> ../benchmark-comment.md
          echo "```" >> ../benchmark-comment.md

      - name: Find benchmark results comment
        uses: peter-evans/find-comment@v3
        id: benchmark-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Benchmark results (master)

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.benchmark-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: 'benchmark-comment.md'
          edit-mode: replace
